package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

var moduleCleaner = regexp.MustCompile(`[^a-zA-Z0-9._/-]+`)

func runInit(args []string) error {
	flags := flag.NewFlagSet("init", flag.ContinueOnError)
	noInstall := flags.Bool("no-install", false, "skip running bun install after scaffolding")
	if err := flags.Parse(args); err != nil {
		return err
	}
	rest := flags.Args()
	if len(rest) != 1 {
		return fmt.Errorf("usage: bifrost init [--no-install] <directory>")
	}
	directory, err := filepath.Abs(rest[0])
	if err != nil {
		return err
	}
	module := moduleCleaner.ReplaceAllString(filepath.Base(directory), "-")
	files := map[string]string{
		"go.mod":                     "module " + module + "\n\ngo 1.25.0\n\nrequire github.com/3-lines-studio/bifrost v1.1.0\n",
		"package.json":               "{\n  \"private\": true,\n  \"type\": \"module\",\n  \"dependencies\": {\n    \"react\": \"19.2.4\",\n    \"react-dom\": \"19.2.4\"\n  },\n  \"devDependencies\": {\n    \"@tailwindcss/vite\": \"4.3.3\",\n    \"@types/react\": \"19.2.14\",\n    \"@types/react-dom\": \"19.2.3\",\n    \"@vitejs/plugin-react\": \"6.0.5\",\n    \"tailwindcss\": \"4.3.3\",\n    \"vite\": \"8.2.1\"\n  }\n}\n",
		"main.go":                    "package main\n\nimport (\n\t\"log\"\n\t\"net/http\"\n\n\t\"github.com/3-lines-studio/bifrost\"\n)\n\nfunc main() {\n\tapp, err := bifrost.New(bifrost.Config{\n\t\tAssets: bifrostAssets,\n\t\tRoutes: []bifrost.Route{bifrost.Server(\"/{$}\", \"pages/home.tsx\", nil)},\n\t})\n\tif err != nil { log.Fatal(err) }\n\tif bifrost.Building() { return }\n\tdefer app.Close(context.Background())\n\tif err := http.ListenAndServe(\":8080\", app.Handler()); err != nil { log.Print(err) }\n}\n",
		"pages/home.tsx":             "import React from 'react';\nimport './style.css';\n\nexport function Head() { return <title>Bifrost</title>; }\nexport function Page() { return <main className=\"p-6\"><h1>Bifrost</h1></main>; }\n",
		"pages/style.css":            "@import \"tailwindcss\";\n",
		"vite.config.ts":             "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nimport tailwindcss from '@tailwindcss/vite';\n\nexport default defineConfig({ plugins: [react(), tailwindcss()] });\n",
		"bifrost.d.ts":               "declare module 'virtual:bifrost/routes' {\n  export interface BifrostRoute {\n    pattern: string;\n    view: string;\n    kind: 'server' | 'static' | 'client';\n  }\n\n  export const routes: BifrostRoute[];\n\n  export function href(pattern: string, params?: Record<string, string | string[]>): string;\n}\n",
		"zz_bifrost_gen.go":          "// Code generated by bifrost. DO NOT EDIT.\n\npackage main\n\nimport (\n\t\"embed\"\n\t\"io/fs\"\n)\n\n//go:embed all:.bifrost\nvar bifrostEmbedded embed.FS\n\nvar bifrostAssets fs.FS = func() fs.FS { assets, err := fs.Sub(bifrostEmbedded, \".bifrost\"); if err != nil { panic(err) }; return assets }()\n",
		".bifrost/embed.placeholder": "generated by bifrost\n",
		".gitignore":                 ".bifrost/*\n!.bifrost/embed.placeholder\nnode_modules/\n",
	}
	// The scaffold uses context in main.
	files["main.go"] = strings.Replace(files["main.go"], "import (\n", "import (\n\t\"context\"\n", 1)
	for name := range files {
		path := filepath.Join(directory, filepath.FromSlash(name))
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("refusing to overwrite %s", path)
		}
	}
	for name, content := range files {
		path := filepath.Join(directory, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		data := []byte(content)
		if filepath.Ext(path) == ".go" {
			formatted, err := format.Source(data)
			if err != nil {
				return fmt.Errorf("format %s: %w", path, err)
			}
			data = formatted
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("Created %s\n", directory)
	if *noInstall {
		fmt.Printf("Run: cd %s && bun install && bifrost dev .\n", directory)
		return nil
	}
	command := exec.Command("bun", "install")
	command.Dir = directory
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	fmt.Println("Running bun install...")
	if err := command.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "bifrost: bun install failed; run it manually before bifrost dev\n")
	}
	return nil
}
