//go:build !windows

package builder

import (
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/3-lines-studio/bifrost/internal/dochtml"
	"github.com/3-lines-studio/bifrost/internal/protocol"
	"github.com/3-lines-studio/bifrost/internal/renderproc"
)

type Options struct {
	Package             string
	Dir                 string
	Output              string
	Development         bool
	ExternalDevelopment bool
	StaticWorkers       int
	SourceMaps          bool
	ViteConfig          string
	OnDescribe          func(protocol.DescribeResult)
	OnOutput            func(string)
	Version             string
}

type packageInfo struct {
	Dir        string
	Name       string
	ImportPath string
	Module     *struct{ Dir string }
}

type viewPlan struct {
	ID         string
	Source     string
	Mode       string
	ClientFile string
	ServerFile string
}

func Build(ctx context.Context, options Options) error {
	if options.Package == "" {
		options.Package = "."
	}
	if options.Dir == "" {
		options.Dir = "."
	}
	info, err := inspectPackage(ctx, options.Dir, options.Package)
	if err != nil {
		return err
	}
	if info.Name != "main" {
		return fmt.Errorf("bifrost: package %s is %q, want main", info.ImportPath, info.Name)
	}
	output := options.Output
	if output == "" {
		output = filepath.Join(info.Dir, ".bifrost")
	} else if !filepath.IsAbs(output) {
		output = filepath.Join(info.Dir, output)
	}
	if err := ensureGeneratedEmbed(info.Dir, info.Name, output); err != nil {
		return err
	}

	describe, err := runDescribe(ctx, options.Dir, options.Package)
	if err != nil {
		return err
	}
	if options.OnDescribe != nil {
		options.OnDescribe(describe)
	}
	generated := protocol.GenerateResult{SpecHash: describe.SpecHash, Limits: describe.Limits}
	if options.ExternalDevelopment {
		if !options.Development {
			return errors.New("external development requires development mode")
		}
		for _, route := range describe.Spec.Routes {
			if route.Kind != "client" {
				return fmt.Errorf("external Vite development requires Client routes; route %q is %s", route.Pattern, route.Kind)
			}
		}
	} else {
		generated, err = runGenerate(ctx, options.Dir, options.Package)
		if err != nil {
			return err
		}
		if generated.SpecHash != describe.SpecHash {
			return fmt.Errorf("bifrost: app declarations changed between describe and generate phases: %s != %s", describe.SpecHash, generated.SpecHash)
		}
		if generated.Limits != describe.Limits {
			return errors.New("bifrost: app limits changed between describe and generate phases")
		}
	}

	temporary, err := os.MkdirTemp(filepath.Dir(output), ".bifrost-build-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(temporary) }()
	if err := os.WriteFile(filepath.Join(temporary, "embed.placeholder"), []byte("generated by bifrost\n"), 0o644); err != nil {
		return err
	}
	for _, directory := range []string{"entries", "dist", "ssr", "pages", "runtime", "public"} {
		if err := os.MkdirAll(filepath.Join(temporary, directory), 0o755); err != nil {
			return err
		}
	}

	buildID := ""
	if options.Development && !options.ExternalDevelopment {
		buildID = digest(strconv.FormatInt(time.Now().UnixNano(), 10))
	}
	plans, routeViews, err := planViews(describe, temporary)
	if err != nil {
		return err
	}
	if err := writeEntries(describe.SourceRoot, temporary, plans, buildID); err != nil {
		return err
	}
	if options.Development && !options.ExternalDevelopment {
		if err := os.WriteFile(filepath.Join(temporary, "entries", "vite-dev.ts"), []byte(renderproc.DevRuntimeSource), 0o600); err != nil {
			return err
		}
	}
	if !options.ExternalDevelopment {
		if err := buildFrontend(ctx, describe, temporary, plans, options.SourceMaps, options.ViteConfig, options.Development); err != nil {
			return err
		}
	}

	needsRender := false
	needsProductionRuntime := false
	for _, route := range describe.Spec.Routes {
		needsRender = needsRender || route.Kind == "static"
		needsProductionRuntime = needsProductionRuntime || route.Kind == "server"
	}
	buildRender := needsRender && !options.Development
	embedRuntime := needsProductionRuntime && !options.Development
	var runtimeRef *protocol.FileRef
	if buildRender || embedRuntime {
		ref, err := buildRuntime(ctx, describe.SourceRoot, temporary)
		if err != nil {
			return err
		}
		if embedRuntime {
			runtimeRef = &ref
		}
	}

	var views []protocol.BuiltView
	var clientFiles []protocol.FileRef
	if options.ExternalDevelopment {
		views, clientFiles, err = collectExternalDevelopmentViews(temporary, plans)
	} else {
		views, clientFiles, err = collectBuiltViews(temporary, plans, options.Development)
	}
	if err != nil {
		return err
	}
	staticWorkers := options.StaticWorkers
	if staticWorkers <= 0 {
		staticWorkers = 4
	}
	routes, err := buildRoutes(ctx, temporary, describe.Spec, generated.Pages, routeViews, views, buildRender, options.Development, staticWorkers, describe.Limits)
	if err != nil {
		return err
	}
	if !options.Development {
		if err := pruneBuildOnlyServerArtifacts(temporary, routes, views); err != nil {
			return err
		}
	}
	if err := os.Remove(filepath.Join(temporary, "runtime", "bifrost-renderer")); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if !embedRuntime {
		if err := os.RemoveAll(filepath.Join(temporary, "runtime")); err != nil {
			return err
		}
	}
	public, err := copyPublic(describe.SourceRoot, temporary)
	if err != nil {
		return err
	}
	if err := validatePublicOwnership(describe.Spec, public); err != nil {
		return err
	}
	bunVersion, _ := commandOutput(ctx, describe.SourceRoot, "bun", "--version")
	viteVersion := readPackageVersion(describe.SourceRoot, "vite")
	reactVersion := readPackageVersion(describe.SourceRoot, "react")
	reactDOMVersion := readPackageVersion(describe.SourceRoot, "react-dom")
	bifrostVersion := options.Version
	if bifrostVersion == "" {
		bifrostVersion = "devel"
	}
	manifest := protocol.Manifest{
		Schema:   protocol.Schema,
		SpecHash: describe.SpecHash,
		BuildID:  buildID,
		Toolchain: protocol.Toolchain{
			Bifrost: bifrostVersion,
			Bun:     strings.TrimSpace(bunVersion),
			Vite:    viteVersion,
			React:   reactVersion,
		},
		Runtime:     runtimeRef,
		Views:       views,
		Routes:      routes,
		ClientFiles: clientFiles,
		Public:      public,
	}
	if runtimeRef != nil {
		manifest.RuntimeCompression = "gzip"
	}
	if manifest.Toolchain.Bun == "" {
		return errors.New("bifrost: cannot determine Bun version")
	}
	if !supportedBunVersion(manifest.Toolchain.Bun) {
		return fmt.Errorf("bifrost: unsupported Bun version %q; V1 requires Bun 1.3 or newer", manifest.Toolchain.Bun)
	}
	if manifest.Toolchain.Vite == "" || !supportedViteVersion(manifest.Toolchain.Vite) {
		return fmt.Errorf("bifrost: unsupported Vite version %q; Bifrost requires Vite 8", manifest.Toolchain.Vite)
	}
	if manifest.Toolchain.React == "" || reactDOMVersion == "" {
		return errors.New("bifrost: cannot determine React and React DOM versions")
	}
	if majorMinorVersion(manifest.Toolchain.React) != majorMinorVersion(reactDOMVersion) {
		return fmt.Errorf("bifrost: React %s and React DOM %s must use the same major.minor version", manifest.Toolchain.React, reactDOMVersion)
	}
	if manifest.BuildID == "" {
		canonical, err := json.Marshal(manifest)
		if err != nil {
			return err
		}
		manifest.BuildID = digestBytes(canonical)
	}
	manifestData, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	manifestData = append(manifestData, '\n')
	if err := os.WriteFile(filepath.Join(temporary, "manifest.json"), manifestData, 0o644); err != nil {
		return err
	}
	if options.ExternalDevelopment {
		current, readErr := os.ReadFile(filepath.Join(output, "manifest.json"))
		refs := slices.Clone(clientFiles)
		for _, asset := range public {
			refs = append(refs, asset.File)
		}
		if readErr == nil && bytes.Equal(current, manifestData) && fileRefsMatch(output, refs) {
			if options.OnOutput != nil {
				options.OnOutput(output)
			}
			return nil
		}
	}
	if !options.Development {
		_ = os.RemoveAll(filepath.Join(temporary, "entries"))
	}

	backup := output + ".old"
	_ = os.RemoveAll(backup)
	if _, err := os.Stat(output); err == nil {
		if err := os.Rename(output, backup); err != nil {
			return err
		}
	}
	if err := os.Rename(temporary, output); err != nil {
		_ = os.Rename(backup, output)
		return err
	}
	_ = os.RemoveAll(backup)
	if options.OnOutput != nil {
		options.OnOutput(output)
	}
	return nil
}

func inspectPackage(ctx context.Context, dir, packagePath string) (packageInfo, error) {
	// -e still reports package identity when a generated go:embed directory was
	// removed by a clean command. ensureGeneratedEmbed repairs it before go run.
	command := exec.CommandContext(ctx, "go", "list", "-e", "-json", packagePath)
	command.Dir = dir
	output, err := command.Output()
	if err != nil {
		return packageInfo{}, commandError(command, err)
	}
	var info packageInfo
	if err := json.Unmarshal(output, &info); err != nil {
		return packageInfo{}, err
	}
	if info.Dir == "" || info.Name == "" {
		return packageInfo{}, fmt.Errorf("bifrost: go list did not resolve package %q", packagePath)
	}
	return info, nil
}

func ensureGeneratedEmbed(packageDir, packageName, output string) error {
	relativeOutput, err := filepath.Rel(packageDir, output)
	if err != nil || relativeOutput == "." || relativeOutput == ".." || strings.HasPrefix(relativeOutput, ".."+string(filepath.Separator)) {
		return errors.New("bifrost: output must be a child of the main package directory")
	}
	embedPath := filepath.ToSlash(relativeOutput)
	if strings.ContainsAny(embedPath, " \t\n") {
		return fmt.Errorf("bifrost: output path %q cannot be used as a go:embed pattern", embedPath)
	}
	if err := os.MkdirAll(output, 0o755); err != nil {
		return err
	}
	placeholder := filepath.Join(output, "embed.placeholder")
	if err := os.WriteFile(placeholder, []byte("generated by bifrost\n"), 0o644); err != nil {
		return err
	}
	content := "// Code generated by bifrost. DO NOT EDIT.\n\npackage " + packageName + "\n\nimport (\n\t\"embed\"\n\t\"io/fs\"\n)\n\n//go:embed all:" + embedPath + "\nvar bifrostEmbedded embed.FS\n\nvar bifrostAssets fs.FS = func() fs.FS {\n\tassets, err := fs.Sub(bifrostEmbedded, " + strconv.Quote(embedPath) + ")\n\tif err != nil { panic(err) }\n\treturn assets\n}()\n"
	formatted, err := format.Source([]byte(content))
	if err != nil {
		return fmt.Errorf("bifrost: format generated embed file: %w", err)
	}
	generatedPath := filepath.Join(packageDir, "zz_bifrost_gen.go")
	if current, err := os.ReadFile(generatedPath); err == nil && bytes.Equal(current, formatted) {
		return nil
	}
	return os.WriteFile(generatedPath, formatted, 0o644)
}

func runDescribe(ctx context.Context, dir, packagePath string) (protocol.DescribeResult, error) {
	var result protocol.DescribeResult
	err := runPhase(ctx, dir, packagePath, "describe", &result)
	return result, err
}

func runGenerate(ctx context.Context, dir, packagePath string) (protocol.GenerateResult, error) {
	var result protocol.GenerateResult
	err := runPhase(ctx, dir, packagePath, "generate", &result)
	return result, err
}

func runPhase(ctx context.Context, dir, packagePath, phase string, result any) error {
	reader, writer, err := os.Pipe()
	if err != nil {
		return err
	}
	defer func() { _ = reader.Close() }()
	command := exec.CommandContext(ctx, "go", "run", packagePath)
	command.Dir = dir
	command.ExtraFiles = []*os.File{writer}
	command.Env = append(os.Environ(), "BIFROST_PHASE="+phase, "BIFROST_FD=3")
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	command.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	if err := command.Start(); err != nil {
		_ = writer.Close()
		return err
	}
	_ = writer.Close()
	decodeErr := json.NewDecoder(reader).Decode(result)
	if command.Process != nil {
		_ = syscall.Kill(-command.Process.Pid, syscall.SIGTERM)
	}
	waitErr := command.Wait()
	if decodeErr != nil {
		if waitErr != nil {
			return fmt.Errorf("bifrost: %s phase: %w", phase, waitErr)
		}
		return fmt.Errorf("bifrost: decode %s phase: %w", phase, decodeErr)
	}
	return nil
}

func planViews(describe protocol.DescribeResult, output string) ([]viewPlan, map[string]string, error) {
	byKey := make(map[string]viewPlan)
	routeViews := make(map[string]string, len(describe.Spec.Routes))
	for _, route := range describe.Spec.Routes {
		mode := "hydrate"
		if route.Kind == "client" {
			mode = "mount"
		}
		id := digest(route.View + "\x00" + mode)
		plan := viewPlan{ID: id, Source: route.View, Mode: mode, ClientFile: filepath.Join(output, "entries", id+"-client.tsx")}
		if mode == "hydrate" {
			plan.ServerFile = filepath.Join(output, "entries", id+"-server.tsx")
		}
		byKey[id] = plan
		routeViews[route.Pattern] = id
	}
	plans := make([]viewPlan, 0, len(byKey))
	for _, plan := range byKey {
		plans = append(plans, plan)
	}
	slices.SortFunc(plans, func(a, b viewPlan) int { return strings.Compare(a.ID, b.ID) })
	return plans, routeViews, nil
}

func writeEntries(sourceRoot, output string, plans []viewPlan, buildID string) error {
	for _, plan := range plans {
		source, err := resolveSourceFile(sourceRoot, plan.Source)
		if err != nil {
			return err
		}
		quoted := strconv.Quote(filepath.ToSlash(source))
		var client string
		if plan.Mode == "mount" {
			client = "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { Page } from " + quoted + ";\nconst root=document.getElementById('app'); if(!root) throw new Error('missing #app'); createRoot(root).render(React.createElement(Page, {}));\n"
		} else {
			client = "import React from 'react';\nimport { hydrateRoot } from 'react-dom/client';\nimport { Page } from " + quoted + ";\nconst node=document.getElementById('__BIFROST_PROPS__'); const props=node?.textContent ? JSON.parse(node.textContent) : {}; const root=document.getElementById('app'); if(!root) throw new Error('missing #app'); hydrateRoot(root, React.createElement(Page, props));\n"
		}
		if buildID != "" {
			client += "const bifrostBuild=" + strconv.Quote(buildID) + ";async function bifrostPoll(){try{const r=await fetch('/_bifrost/build-id?wait='+bifrostBuild,{cache:'no-store'});if(r.ok){if((await r.text())!==bifrostBuild){location.reload();return;}setTimeout(bifrostPoll,0);}else{setTimeout(bifrostPoll,500);}}catch{setTimeout(bifrostPoll,500);}}bifrostPoll();\n"
		}
		if err := os.WriteFile(plan.ClientFile, []byte(client), 0o644); err != nil {
			return err
		}
		if plan.ServerFile != "" {
			server := "import React from 'react';\nimport { renderToReadableStream, renderToString } from 'react-dom/server';\nimport * as M from " + quoted + ";\nexport async function render(props, signal) { let renderError; const head = typeof M.Head === 'function' ? renderToString(React.createElement(M.Head, props)) : ''; const source = await renderToReadableStream(React.createElement(M.Page, props), { signal, onError(error) { renderError = error instanceof Error ? error : new Error(String(error)); } }); const reader = source.getReader(); const body = new ReadableStream({ async pull(controller) { try { const result = await reader.read(); if (renderError) throw renderError; if (result.done) controller.close(); else controller.enqueue(result.value); } catch (error) { controller.error(error); } }, cancel(reason) { return reader.cancel(reason); } }); return { head, body }; }\n"
			if err := os.WriteFile(plan.ServerFile, []byte(server), 0o644); err != nil {
				return err
			}
		}
	}
	return nil
}

func resolveSourceFile(sourceRoot, sourcePath string) (string, error) {
	resolvedRoot, err := filepath.EvalSymlinks(sourceRoot)
	if err != nil {
		return "", fmt.Errorf("bifrost: resolve source root: %w", err)
	}
	resolvedSource, err := filepath.EvalSymlinks(filepath.Join(sourceRoot, filepath.FromSlash(sourcePath)))
	if err != nil {
		return "", fmt.Errorf("bifrost: resolve view %q: %w", sourcePath, err)
	}
	relative, err := filepath.Rel(resolvedRoot, resolvedSource)
	if err != nil || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("bifrost: view %q escapes source root through a symlink", sourcePath)
	}
	return resolvedSource, nil
}

type viteTargetRequest struct {
	Entries  map[string]string `json:"entries"`
	OutDir   string            `json:"outDir"`
	Manifest string            `json:"manifest"`
}

type viteBuildRequest struct {
	Root       string               `json:"root"`
	SourceMaps bool                 `json:"sourceMaps"`
	ConfigFile string               `json:"configFile,omitempty"`
	Routes     []protocol.RouteSpec `json:"routes"`
	Client     viteTargetRequest    `json:"client"`
	Server     *viteTargetRequest   `json:"server,omitempty"`
}

func buildFrontend(ctx context.Context, describe protocol.DescribeResult, output string, plans []viewPlan, sourceMaps bool, viteConfig string, development bool) error {
	if len(plans) == 0 {
		return nil
	}
	clientEntries := make(map[string]string, len(plans))
	serverEntries := make(map[string]string)
	for _, plan := range plans {
		clientEntries[plan.ID+"-client"] = filepath.ToSlash(plan.ClientFile)
		if !development && plan.ServerFile != "" {
			serverEntries[plan.ID+"-server"] = filepath.ToSlash(plan.ServerFile)
		}
	}
	request := viteBuildRequest{
		Root:       describe.SourceRoot,
		SourceMaps: sourceMaps,
		ConfigFile: viteConfig,
		Routes:     describe.Spec.Routes,
		Client: viteTargetRequest{
			Entries:  clientEntries,
			OutDir:   filepath.Join(output, "dist"),
			Manifest: "client-manifest.json",
		},
	}
	if !development && len(serverEntries) > 0 {
		request.Server = &viteTargetRequest{
			Entries:  serverEntries,
			OutDir:   filepath.Join(output, "ssr"),
			Manifest: "server-manifest.json",
		}
	}
	data, err := json.Marshal(request)
	if err != nil {
		return err
	}
	runner := filepath.Join(output, "entries", "vite-runner.ts")
	if err := os.WriteFile(runner, []byte(viteRunnerSource), 0o600); err != nil {
		return err
	}
	command := exec.CommandContext(ctx, "bun", "run", runner)
	command.Dir = describe.SourceRoot
	command.Stdin = bytes.NewReader(data)
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	command.Env = append(os.Environ(), "BIFROST=1", "BIFROST_BUILD=1")
	if err := command.Run(); err != nil {
		return commandError(command, err)
	}
	return nil
}

func buildRuntime(ctx context.Context, sourceRoot, output string) (protocol.FileRef, error) {
	source := filepath.Join(output, "entries", "runtime.ts")
	if err := os.WriteFile(source, []byte(renderproc.RuntimeSource), 0o644); err != nil {
		return protocol.FileRef{}, err
	}
	destination := filepath.Join(output, "runtime", "bifrost-renderer")
	command := exec.CommandContext(ctx, "bun", "build", source, "--compile", "--minify", "--outfile", destination)
	command.Dir = sourceRoot
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return protocol.FileRef{}, commandError(command, err)
	}
	compressed := destination + ".gz"
	if err := gzipFile(destination, compressed); err != nil {
		return protocol.FileRef{}, err
	}
	return fileRef(output, compressed)
}

func gzipFile(sourcePath, destination string) error {
	source, err := os.Open(sourcePath)
	if err != nil {
		return err
	}
	defer func() { _ = source.Close() }()
	output, err := os.Create(destination)
	if err != nil {
		return err
	}
	writer, err := gzip.NewWriterLevel(output, gzip.BestCompression)
	if err != nil {
		_ = output.Close()
		return err
	}
	writer.ModTime = time.Time{}
	writer.Name = ""
	_, copyErr := io.Copy(writer, source)
	closeGzipErr := writer.Close()
	closeOutputErr := output.Close()
	if copyErr != nil {
		return copyErr
	}
	if closeGzipErr != nil {
		return closeGzipErr
	}
	return closeOutputErr
}

type viteManifestEntry struct {
	File           string   `json:"file"`
	Name           string   `json:"name"`
	Src            string   `json:"src"`
	IsEntry        bool     `json:"isEntry"`
	Imports        []string `json:"imports"`
	DynamicImports []string `json:"dynamicImports"`
	CSS            []string `json:"css"`
	Assets         []string `json:"assets"`
}

type viteManifest map[string]viteManifestEntry

func collectExternalDevelopmentViews(output string, plans []viewPlan) ([]protocol.BuiltView, []protocol.FileRef, error) {
	views := make([]protocol.BuiltView, len(plans))
	files := make([]protocol.FileRef, len(plans))
	for index, plan := range plans {
		if plan.Mode != "mount" || plan.ServerFile != "" {
			return nil, nil, errors.New("external Vite development requires mount views")
		}
		ref, err := fileRef(output, plan.ClientFile)
		if err != nil {
			return nil, nil, err
		}
		views[index] = protocol.BuiltView{ID: plan.ID, Source: plan.Source, Mode: plan.Mode, Client: protocol.AssetSet{Entry: ref}}
		files[index] = ref
	}
	return views, files, nil
}

func collectBuiltViews(output string, plans []viewPlan, development bool) ([]protocol.BuiltView, []protocol.FileRef, error) {
	clientManifestPath := filepath.Join(output, "dist", "client-manifest.json")
	clientManifest, err := readViteManifest(clientManifestPath)
	if err != nil {
		return nil, nil, err
	}
	if err := os.Remove(clientManifestPath); err != nil {
		return nil, nil, err
	}
	var serverManifest viteManifest
	serverManifestPath := filepath.Join(output, "ssr", "server-manifest.json")
	if !development {
		if _, err := os.Stat(serverManifestPath); err == nil {
			serverManifest, err = readViteManifest(serverManifestPath)
			if err != nil {
				return nil, nil, err
			}
			if err := os.Remove(serverManifestPath); err != nil {
				return nil, nil, err
			}
		}
	}
	clientFiles, err := collectRefs(output, filepath.Join(output, "dist"))
	if err != nil {
		return nil, nil, err
	}
	views := make([]protocol.BuiltView, 0, len(plans))
	for _, plan := range plans {
		clientKey, clientRecord, err := viteEntry(clientManifest, plan.ID+"-client")
		if err != nil {
			return nil, nil, err
		}
		clientEntry, err := fileRef(output, filepath.Join(output, "dist", filepath.FromSlash(clientRecord.File)))
		if err != nil {
			return nil, nil, err
		}
		importPaths, stylePaths := viteClientDependencies(clientManifest, clientKey)
		imports, err := refsForRelativePaths(output, filepath.Join(output, "dist"), importPaths)
		if err != nil {
			return nil, nil, err
		}
		styles, err := refsForRelativePaths(output, filepath.Join(output, "dist"), stylePaths)
		if err != nil {
			return nil, nil, err
		}
		view := protocol.BuiltView{
			ID:     plan.ID,
			Source: plan.Source,
			Mode:   plan.Mode,
			Client: protocol.AssetSet{Entry: clientEntry, Imports: imports, Styles: styles},
		}
		if !development && plan.ServerFile != "" {
			_, serverRecord, err := viteEntry(serverManifest, plan.ID+"-server")
			if err != nil {
				return nil, nil, err
			}
			entry, err := fileRef(output, filepath.Join(output, "ssr", filepath.FromSlash(serverRecord.File)))
			if err != nil {
				return nil, nil, err
			}
			serverPaths := viteServerDependencies(serverManifest, plan.ID+"-server")
			serverImports, err := refsForRelativePaths(output, filepath.Join(output, "ssr"), serverPaths)
			if err != nil {
				return nil, nil, err
			}
			view.Server = &protocol.ServerAssets{Entry: entry, Imports: serverImports}
		}
		views = append(views, view)
	}
	return views, clientFiles, nil
}

func readViteManifest(filePath string) (viteManifest, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("bifrost: read Vite manifest: %w", err)
	}
	var manifest viteManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, fmt.Errorf("bifrost: decode Vite manifest: %w", err)
	}
	return manifest, nil
}

func viteEntry(manifest viteManifest, name string) (string, viteManifestEntry, error) {
	for key, entry := range manifest {
		if entry.IsEntry && entry.Name == name {
			return key, entry, nil
		}
	}
	return "", viteManifestEntry{}, fmt.Errorf("bifrost: Vite manifest has no entry %q", name)
}

func viteClientDependencies(manifest viteManifest, entryKey string) ([]string, []string) {
	seenModules := make(map[string]struct{})
	seenImports := make(map[string]struct{})
	seenStyles := make(map[string]struct{})
	var imports []string
	var styles []string
	var walk func(string)
	walk = func(key string) {
		if _, exists := seenModules[key]; exists {
			return
		}
		seenModules[key] = struct{}{}
		entry, exists := manifest[key]
		if !exists {
			return
		}
		for _, css := range entry.CSS {
			if _, exists := seenStyles[css]; !exists {
				seenStyles[css] = struct{}{}
				styles = append(styles, css)
			}
		}
		for _, imported := range entry.Imports {
			if record, exists := manifest[imported]; exists {
				if _, exists := seenImports[record.File]; !exists {
					seenImports[record.File] = struct{}{}
					imports = append(imports, record.File)
				}
			}
			walk(imported)
		}
	}
	walk(entryKey)
	return imports, styles
}

func viteServerDependencies(manifest viteManifest, entryName string) []string {
	entryKey, _, err := viteEntry(manifest, entryName)
	if err != nil {
		return nil
	}
	seen := make(map[string]struct{})
	files := make(map[string]struct{})
	var walk func(string)
	walk = func(key string) {
		if _, exists := seen[key]; exists {
			return
		}
		seen[key] = struct{}{}
		entry, exists := manifest[key]
		if !exists {
			return
		}
		for _, imported := range append(slices.Clone(entry.Imports), entry.DynamicImports...) {
			if record, exists := manifest[imported]; exists {
				files[record.File] = struct{}{}
			}
			walk(imported)
		}
	}
	walk(entryKey)
	return sortedKeys(files)
}

func refsForRelativePaths(root, directory string, paths []string) ([]protocol.FileRef, error) {
	refs := make([]protocol.FileRef, 0, len(paths))
	for _, relative := range paths {
		ref, err := fileRef(root, filepath.Join(directory, filepath.FromSlash(relative)))
		if err != nil {
			return nil, err
		}
		refs = append(refs, ref)
	}
	return refs, nil
}

func sortedKeys(values map[string]struct{}) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	return keys
}

func pruneBuildOnlyServerArtifacts(output string, routes []protocol.BuiltRoute, views []protocol.BuiltView) error {
	needed := make(map[string]struct{})
	for _, route := range routes {
		if route.Kind == "server" {
			needed[route.ViewID] = struct{}{}
		}
	}
	keptFiles := make(map[string]struct{})
	for i := range views {
		if views[i].Server == nil {
			continue
		}
		if _, keep := needed[views[i].ID]; !keep {
			views[i].Server = nil
			continue
		}
		keptFiles[views[i].Server.Entry.Path] = struct{}{}
		for _, file := range views[i].Server.Imports {
			keptFiles[file.Path] = struct{}{}
		}
	}
	if len(needed) == 0 {
		return os.RemoveAll(filepath.Join(output, "ssr"))
	}
	return filepath.WalkDir(filepath.Join(output, "ssr"), func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil || entry.IsDir() {
			return walkErr
		}
		relative, err := filepath.Rel(output, filePath)
		if err != nil {
			return err
		}
		if _, keep := keptFiles[filepath.ToSlash(relative)]; !keep {
			return os.Remove(filePath)
		}
		return nil
	})
}

func collectRefs(root, directory string) ([]protocol.FileRef, error) {
	if _, err := os.Stat(directory); errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	var refs []protocol.FileRef
	err := filepath.WalkDir(directory, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil || entry.IsDir() {
			return walkErr
		}
		ref, err := fileRef(root, filePath)
		if err != nil {
			return err
		}
		refs = append(refs, ref)
		return nil
	})
	slices.SortFunc(refs, func(a, b protocol.FileRef) int { return strings.Compare(a.Path, b.Path) })
	return refs, err
}

func buildRoutes(ctx context.Context, output string, spec protocol.Spec, generated []protocol.GeneratedPage, routeViews map[string]string, views []protocol.BuiltView, needsRender, development bool, staticWorkers int, limits protocol.RuntimeLimits) ([]protocol.BuiltRoute, error) {
	pagesByPattern := make(map[string][]protocol.GeneratedPage)
	for _, page := range generated {
		pagesByPattern[page.Pattern] = append(pagesByPattern[page.Pattern], page)
	}
	viewMap := make(map[string]protocol.BuiltView, len(views))
	for _, view := range views {
		viewMap[view.ID] = view
	}
	var process *renderproc.Process
	var err error
	if needsRender {
		process, err = renderproc.Start(filepath.Join(output, "runtime", "bifrost-renderer"), output)
		if err != nil {
			return nil, err
		}
		defer func() { _ = process.Close(context.Background()) }()
	}

	routes := make([]protocol.BuiltRoute, 0, len(spec.Routes))
	for _, route := range spec.Routes {
		built := protocol.BuiltRoute{Pattern: route.Pattern, Kind: route.Kind, ViewID: routeViews[route.Pattern]}
		if route.Kind == "static" {
			view := viewMap[built.ViewID]
			var documents []protocol.Document
			var err error
			if development {
				documents, err = writeDevelopmentStaticDocuments(output, view, pagesByPattern[route.Pattern])
			} else {
				documents, err = renderStaticPages(ctx, process, output, view, pagesByPattern[route.Pattern], staticWorkers, limits)
			}
			if err != nil {
				return nil, err
			}
			built.Documents = documents
		}
		routes = append(routes, built)
	}
	return routes, nil
}

func writeDevelopmentStaticDocuments(output string, view protocol.BuiltView, pages []protocol.GeneratedPage) ([]protocol.Document, error) {
	documents := make([]protocol.Document, len(pages))
	for index, page := range pages {
		document, err := renderDocument(view.Client, page.Props, page.Document, nil, "")
		if err != nil {
			return nil, err
		}
		filePath := filepath.Join(output, "pages", digest(page.Path)+".html")
		if err := os.WriteFile(filePath, []byte(document), 0o644); err != nil {
			return nil, err
		}
		ref, err := fileRef(output, filePath)
		if err != nil {
			return nil, err
		}
		documents[index] = protocol.Document{Path: page.Path, File: ref, Props: page.Props, Document: page.Document}
	}
	return documents, nil
}

func renderStaticPages(ctx context.Context, process *renderproc.Process, output string, view protocol.BuiltView, pages []protocol.GeneratedPage, workers int, limits protocol.RuntimeLimits) ([]protocol.Document, error) {
	if len(pages) == 0 {
		return nil, nil
	}
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	documents := make([]protocol.Document, len(pages))
	jobs := make(chan int)
	var group sync.WaitGroup
	var firstErr error
	var errorMu sync.Mutex
	worker := func() {
		defer group.Done()
		for index := range jobs {
			page := pages[index]
			collector := &renderCollector{maxHead: limits.MaxHeadBytes, maxFrame: limits.MaxFrameBytes}
			entry := filepath.Join(output, filepath.FromSlash(view.Server.Entry.Path))
			if err := process.Render(ctx, entry, page.Props, collector); err != nil {
				errorMu.Lock()
				if firstErr == nil {
					firstErr = fmt.Errorf("bifrost: prerender %q: %w", page.Path, err)
					cancel()
				}
				errorMu.Unlock()
				continue
			}
			document, err := renderDocument(view.Client, page.Props, page.Document, collector.head, collector.body.String())
			if err != nil {
				errorMu.Lock()
				if firstErr == nil {
					firstErr = err
					cancel()
				}
				errorMu.Unlock()
				continue
			}
			filePath := filepath.Join(output, "pages", digest(page.Path)+".html")
			if err := os.WriteFile(filePath, []byte(document), 0o644); err != nil {
				errorMu.Lock()
				if firstErr == nil {
					firstErr = err
					cancel()
				}
				errorMu.Unlock()
				continue
			}
			ref, err := fileRef(output, filePath)
			if err != nil {
				errorMu.Lock()
				if firstErr == nil {
					firstErr = err
					cancel()
				}
				errorMu.Unlock()
				continue
			}
			documents[index] = protocol.Document{Path: page.Path, File: ref, Props: page.Props, Document: page.Document}
		}
	}
	if workers > len(pages) {
		workers = len(pages)
	}
	for range workers {
		group.Add(1)
		go worker()
	}
sending:
	for index := range pages {
		select {
		case jobs <- index:
		case <-ctx.Done():
			break sending
		}
	}
	close(jobs)
	group.Wait()
	if firstErr != nil {
		return nil, firstErr
	}
	return documents, nil
}

type renderCollector struct {
	head     []byte
	body     bytes.Buffer
	maxHead  int
	maxFrame int
}

func (s *renderCollector) Head(head []byte) error {
	if s.head != nil {
		return errors.New("duplicate head")
	}
	if len(head) > s.maxHead {
		return fmt.Errorf("head exceeds %d bytes", s.maxHead)
	}
	s.head = append([]byte{}, head...)
	return nil
}
func (s *renderCollector) Body(body []byte) error {
	if len(body) > s.maxFrame {
		return fmt.Errorf("body frame exceeds %d bytes", s.maxFrame)
	}
	_, err := s.body.Write(body)
	return err
}

func renderDocument(assets protocol.AssetSet, props []byte, document protocol.DocumentAttributes, head []byte, body string) (string, error) {
	shell, err := dochtml.NewShell(assets)
	if err != nil {
		return "", err
	}
	var output bytes.Buffer
	if err := shell.Render(&output, head, []byte(body), props, document); err != nil {
		return "", err
	}
	return output.String(), nil
}

func validatePublicOwnership(spec protocol.Spec, assets []protocol.PublicAsset) error {
	mux := http.NewServeMux()
	for _, route := range spec.Routes {
		mux.Handle("GET "+route.Pattern, http.HandlerFunc(func(http.ResponseWriter, *http.Request) {}))
	}
	for _, asset := range assets {
		request := &http.Request{Method: http.MethodGet, URL: &url.URL{Path: asset.URL}}
		_, pattern := mux.Handler(request)
		if pattern != "" && !strings.Contains(pattern, "{path...}") {
			return fmt.Errorf("bifrost: public URL %q conflicts with page pattern %q", asset.URL, strings.TrimPrefix(pattern, "GET "))
		}
	}
	return nil
}

func copyPublic(sourceRoot, output string) ([]protocol.PublicAsset, error) {
	root := filepath.Join(sourceRoot, "public")
	if _, err := os.Stat(root); errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	var assets []protocol.PublicAsset
	err := filepath.WalkDir(root, func(filePath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil || entry.IsDir() {
			return walkErr
		}
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("bifrost: public symlink %q is not allowed", filePath)
		}
		rel, err := filepath.Rel(root, filePath)
		if err != nil {
			return err
		}
		destination := filepath.Join(output, "public", rel)
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}
		if err := copyFile(filePath, destination); err != nil {
			return err
		}
		publicURL := "/" + filepath.ToSlash(rel)
		if strings.ContainsAny(publicURL, " ?#%{}") {
			return fmt.Errorf("bifrost: public file %q requires URL escaping; rename it", rel)
		}
		ref, err := fileRef(output, destination)
		if err != nil {
			return err
		}
		assets = append(assets, protocol.PublicAsset{URL: publicURL, File: ref})
		return nil
	})
	slices.SortFunc(assets, func(a, b protocol.PublicAsset) int { return strings.Compare(a.URL, b.URL) })
	return assets, err
}

func fileRef(root, filePath string) (protocol.FileRef, error) {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return protocol.FileRef{}, err
	}
	rel, err := filepath.Rel(root, filePath)
	if err != nil {
		return protocol.FileRef{}, err
	}
	return protocol.FileRef{Path: filepath.ToSlash(rel), Hash: digestBytes(data), Size: int64(len(data))}, nil
}

func fileRefsMatch(root string, refs []protocol.FileRef) bool {
	for _, expected := range refs {
		actual, err := fileRef(root, filepath.Join(root, filepath.FromSlash(expected.Path)))
		if err != nil || actual != expected {
			return false
		}
	}
	return true
}

func copyFile(sourcePath, destination string) error {
	source, err := os.Open(sourcePath)
	if err != nil {
		return err
	}
	defer func() { _ = source.Close() }()
	destinationFile, err := os.Create(destination)
	if err != nil {
		return err
	}
	_, copyErr := io.Copy(destinationFile, source)
	closeErr := destinationFile.Close()
	if copyErr != nil {
		return copyErr
	}
	return closeErr
}

func digest(value string) string { return digestBytes([]byte(value)) }
func digestBytes(value []byte) string {
	hash := sha256.Sum256(value)
	return hex.EncodeToString(hash[:])
}
func commandOutput(ctx context.Context, dir, name string, args ...string) (string, error) {
	command := exec.CommandContext(ctx, name, args...)
	command.Dir = dir
	output, err := command.Output()
	return string(output), err
}

func commandError(command *exec.Cmd, err error) error {
	var exit *exec.ExitError
	if errors.As(err, &exit) {
		return fmt.Errorf("bifrost: %s: %w\n%s", strings.Join(command.Args, " "), err, exit.Stderr)
	}
	return fmt.Errorf("bifrost: %s: %w", strings.Join(command.Args, " "), err)
}

func supportedViteVersion(version string) bool {
	parts := strings.Split(strings.TrimSpace(version), ".")
	major, err := strconv.Atoi(parts[0])
	return err == nil && major == 8
}

func supportedBunVersion(version string) bool {
	parts := strings.Split(strings.TrimSpace(version), ".")
	if len(parts) < 2 {
		return false
	}
	major, majorErr := strconv.Atoi(parts[0])
	minor, minorErr := strconv.Atoi(parts[1])
	return majorErr == nil && minorErr == nil && major == 1 && minor >= 3
}

func majorMinorVersion(version string) string {
	parts := strings.Split(version, ".")
	if len(parts) < 2 {
		return ""
	}
	return parts[0] + "." + parts[1]
}

func readPackageVersion(root, name string) string {
	current, err := filepath.Abs(root)
	if err != nil {
		return ""
	}
	for {
		if version := packageVersionFile(filepath.Join(current, "node_modules", filepath.FromSlash(name), "package.json")); version != "" {
			return version
		}
		if version := declaredPackageVersion(filepath.Join(current, "package.json"), name); version != "" {
			return version
		}
		parent := filepath.Dir(current)
		if parent == current {
			return ""
		}
		current = parent
	}
}

func packageVersionFile(filePath string) string {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return ""
	}
	var installed struct {
		Version string `json:"version"`
	}
	if json.Unmarshal(data, &installed) != nil {
		return ""
	}
	return installed.Version
}

func declaredPackageVersion(filePath, name string) string {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return ""
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if json.Unmarshal(data, &pkg) != nil {
		return ""
	}
	if version := pkg.Dependencies[name]; version != "" {
		return version
	}
	return pkg.DevDependencies[name]
}
