// Code generated by bifrost. DO NOT EDIT.

package main

import (
	"embed"
	"io/fs"
)

//go:embed all:.bifrost
var bifrostEmbedded embed.FS

var bifrostAssets fs.FS = func() fs.FS {
	assets, err := fs.Sub(bifrostEmbedded, ".bifrost")
	if err != nil {
		panic(err)
	}
	return assets
}()
