dev:
	BIFROST_DEV=1 air -c .air.toml

build:
	go run github.com/3-lines-studio/bifrost/cmd/bifrost@latest build ./main.go --go-build

start: build
	./tmp/app

doctor:
	go run github.com/3-lines-studio/bifrost/cmd/bifrost@latest doctor .
